INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'Olha', 'Se', 'Voce', 'Nao', 'Me');
INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'Ama', 'Entao', 'Nao', 'Me', 'Ligue');
INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'Nao', 'Fique', 'Me', 'Fazendo', 'Queixa');
INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'Nao', 'Faca', 'Como', 'As', 'Outras');
INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'Tem', 'Feito', 'Que', 'Minha', 'Vida');
INSERT INTO STUDENT(NAME, EMAIL, ADDRESS, PHONENUMBER, COURSE) VALUES ( 'E', 'Sofreno', 'Que', 'Por', 'Causa');
